### ISSUE TITLE
Prompt improvements

### ISSUE THREAD

**Issue by AlanGreene** [AlanGreene/starter#33]
Recently adopted [starship](https://starship.rs) instead of my collection of homegrown scripts to manage the prompt (including styling).

While it seems to be a general improvement (in terms of maintenance, feature set, and perfromance), I've noticed a few little annoyances over the past couple of weeks using it:
- [ ] panics if current directory is deleted (known issue, awaiting release)
- [ ] `kubeon`/`kubeoff` affect all sessions since they're updating the starship config, can it use an env var like my previous implementation?

Some other changes to consider:
- [ ] remove user and hostname unless they're root or a remote session (i.e. SSH)

**Comment by AlanGreene** [comment]
Also see https://github.com/ohmybash/oh-my-bash

**Comment by AlanGreene** [comment]
Starship - share your custom commands / modules
https://github.com/starship/starship/discussions/1252

**Comment by AlanGreene** [comment]
starship kubernetes config
```toml
[kubernetes]
symbol = '☸ '
disabled = true
detect_files = ['Dockerfile']
format = '[$symbol$context( \($namespace\))]($style) '
contexts = [
  { context_pattern = "arn:aws:eks:us-west-2:1234567890:cluster/my-cluster", style = "green", context_alias = "my-cluster", symbol = " " },
]
```
